apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: blue
  name: deploy-role
rules:
- apiGroups: ["extensions", "apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["get", "watch", "list", "create"]
