##Set Node Affinity to the deployment to place the pods on node01 only based on the label color=blue.
##~# kubectl label nodes node01 color=blue

apiVersion: apps/v1
kind: Deployment
metadata:

  labels:
    app: blue
  name: blue
  namespace: default
spec:
 
  replicas: 3
  selector:
    matchLabels:
      app: blue
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - image: nginx
        name: nginx

      affinity:
       nodeAffinity:
         requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
           - matchExpressions:
             - key: color
               operator: In
               values:
               - blue
