apiVersion: v1
kind: Service
metadata:
  name: mylins-webapp
spec:
  
  selector:
    release : "0-5"
  
  ports:
  - name : http
    port: 80
    nodePort: 30080

  type: NodePort


---

apiVersion: v1
kind: Service
metadata:
  name: mylins-queue
spec:
  
  selector:
    app: queue

  ports:
  - name : http
    port: 8161
    nodePort: 30081

  type: NodePort

