apiVersion: v1
kind: Pod
metadata:
  name: mylins-webapp-release0
  labels:
    app: webapp
    release: "0"

spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0


---

#Release 0-5 pod

apiVersion: v1
kind: Pod
metadata:
  name: mylins-webapp-release0-5
  labels:
    app: webapp
    release: "0-5"

spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
###Queue Pod

apiVersion: v1
kind: Pod
metadata:
  name: mylins-queue
  labels:
    app: queue
    

spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1