
apiVersion: apps/v1
kind: Deployment
metadata:
  name : webapp
spec:
  minReadySeconds : 10
  selector:
    matchLabels:
      app: webapp
  replicas : 3
  template:
    metadata:
      labels:
        app: webapp

    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5



---
###Queue Pod

apiVersion: v1
kind: Pod
metadata:
  name: mylins-queue
  labels:
    app: queue
    

spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1