global:
  slack_api_url: 'enter your webhook URL here. Leave the quote marks in place'
route:
  group_by: ['alertname']
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 10m
  receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
  - channel: '#alerts'
    icon_emoji: ':bell:'
    send_resolved: true
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}\nmessage: {{ .CommonAnnotations.message }}"
    
    
    /* commands used
    ~]# k get secret -n monitoring alertmanager-monitoring-kube-prometheus-alertmanager -o yaml
    ~]# echo Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0KcmVjZWl2ZXJzOgotIG5 |base64 -d
    ~]# k delete secret -n monitoring alertmanager-monitoring-kube-prometheus-alertmanager
    ~]# k create secret generic --from-file=alertmanager.yaml -n monitoring alertmanager-monitoring-kube-prometheus-alertmanager
    */
