apiVersion: apps/v1
kind: Deployment
metadata:
  name: bad-deployment
spec:
  selector:
    matchLabels:
      app: bad
  replicas: 2 
  template:
    metadata:
      labels:
        app: bad
    spec:
      containers:
      - name: bad
        image: ubuntu:18.04
        command: ["10 print('it is 1982')\ni20 goto 10"]
